customhost = "database-1.calxmlmpfagm.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "yongchuan-employee"
customregion = "us-east-1"
